import { FC } from 'react'

import deliveryData from '@/data/delivery.json'
import ISection from '@/shared/interfaces/ISection'

import styles from './DeliveryAndReturn.module.scss'
import { Russo_One } from 'next/font/google'
import Navigation from '../Navigation/Navigation'


const russo = Russo_One({
    subsets: ['latin'],
    weight: '400'
})

const DeliveryAndReturn: FC = () => {
    const { title }: ISection = deliveryData.section;

    return (
        <section className={styles.section} >
            <div className="container">
            <Navigation/>
                <div className={styles.wrapper}>
                    <h2 className={styles.title}>
                        <span className={russo.className}>{title}</span>
                    </h2>
                    <p className={styles.text}>
                        1A Renkaat OY, Y-tunnus 3104581-8 (jäljempänä elinkeinonharjoittaja) ja kuluttaja, joka tekee tilauksen 1arenkaat.fi-verkkokaupassa ja tunnistaa itsensä syöttämällä henkilökohtaiset tiedot tilaukseen, teki tämän verkkokaupan käyttöoikeussopimuksen .1. Verkkokauppa <br />
                        1.1. 1arenkaat.fi on kauppiaan luoma verkkokauppa, jonka kautta tuotteita myydään kuluttajille.2. YLEISET SÄÄNNÖKSET <br />
                        2.1. Sopimuksen osapuolia ohjaavat keskinäisiä suhteitaan Suomen tasavallan lait ja muut lait sekä e-kaupan käyttösopimuksessa oleva sopimus.<br />
                        2.2. Kauppiaalla on oikeus tehdä muutoksia tarjottuun verkkokauppapalveluun milloin tahansa.<br />
                        2.3. Elinkeinonharjoittajalla on oikeus muuttaa yksipuolisesti käyttöoikeusehtoja ilman velvollisuutta ilmoittaa siitä kuluttajalle.3. TUOTTEET JA OSTOKSEN TEKEMINENKuluttajalla on mahdollisuus valita sopiva tuote 1arenkaat.fi -sivustolta ja lisätä se ostoskoriin. Verkkosivusto kuvaa tavarat sekä havainnollisina että todellisina kuvina.<br />
                        3.1. Kuluttajalla on mahdollisuus valita oikea tuote vanteen koon mukaan ja lisätä se ostoskoriin. Voit sitten etsiä verkkosivustolta muita sinua kiinnostavia vanteiden kokoja ja lisätä ne tarvittaessa ostoskoriin. Renkaiden ja vanteiden on esitetty 4, 3, 2 ja 1 määränä. Ei ole mahdollista ostaa yhtä vanteen (1 kpl.) ja paria (2 kpl.) sarjastä. Voisi kirjoittaa sähköpostin ostaaksesi yhden vanteen sarjastä.<br />
                        3.2. Jos muita valintoja ei ole tehty, alla olevat toimitustiedot on täytettävä ja kuljetustapa valittava. Ennen kuin ostat, tarkista annettujen tietojen oikeellisuus, kiinnitä huomiota tuotetietoihin (tuotteen kunto, sijainti, määrä) ja varmista vanteen koko on oike. Seuraavaksi sinun tulee lukea ja hyväksyä 1arenkaat.fi: n ostoehdot ja painaa OSTAA-painiketta.<br />
                        3.3. Voit maksaa tavaroista kokonaisuudessaan verkkosivustolla. Koko lasku lähetetään automaattisesti kuluttajan kirjoittamaan sähköpostiin.<br />
                        3.4. Tavaroiden maksu suoritetaan Montonion kautta. Maksuvaihtoehdot: -Suomi: Aktia, Ålandin pankki, Danske, Handelsbanken, Nordea, Oma Säästopankki, Pohjola, POP Pankki, S-Pankki, Säästopankki-Visa / Mastercard -kortti. Kauppiaan pankkien tiedot näkyvät verkkosivustolla. Paina seuraavaksi OSTAA-painiketta. Sitten kuluttaja ohjataan Internet-pankkiin. Jos maksu on suoritettu Internet-pankissa, on erittäin tärkeää muistaa, että kuluttaja palaa takaisin 1arenkaat.fi -sivustolle, jolla osto tehtiin. Paina Internet-pankissa Takaisin kauppiaan-painiketta.3.5. Meie kumppaneita osamaksujen alalla ovat…<br />
                        3.6. Kuluttajat voivat tilata tavaroita ilmaiseksi 1arenkaat.fi -toimistossä, joka sijaitsee Helsingissä, Valokaari 10: ssä tai yhteistyökumppaneista. Tavarat voidaan tilata myös kuluttajan ilmoittamaan osoitteeseen. Jälkimmäisessä tapauksessa tavaroiden lähettämisen edellytyksenä on maksaa koko summa tilauksen mukaan. Jos kuluttajan osoite on Manner-Suomen sisällä, toimitus on 25 eur 2 kpl ja 40 eur 4kpl ja en riippuu toimituspaikasta. Suomessa Matkahuollon hinnastot ovat voimassa. Hinnat voidaan aina kysyaa toimittajalta. Toimitushinta lisätään automaattisesti tavaroiden hintaan valitsemalla oikea toimitusmenetelmä ostoksen yhteydessä.3.7. Haluttaessa on mahdollista suorittaa renkaanvaihto 1arenkaat.fi -toimistossa Helsingissä tai yhteistyökumppaneilla.3.8. Elinkeinonharjoittajan ja kuluttajan välisen sopimuksen katsotaan tehdyn alkaen tilausvahvistuksen mukaan maksettavan määrän vastaanottamisesta 1A Renkaat OY: n käyttötilille.3.9. Verkkokaupasta tehty ”maksamaton tilaus”, josta kuluttaja ei ole suorittanut siirtoa 3 työpäivän kuluessa, peruutetaan.4. HINNAT4.1. Kaikki verkkokaupan hinnat ovat euroissa ja sisältävät arvonlisäveron.4.2. Neljän (4) ja enammään renkaan tilaamisen kuljetuskustannukset Suomessä ovat 25-40eur.<br />
                        4.3. Jos tilaus tehdään alle neljästä (4) renkaasta, kuljetuksen hinta on 25 – 40 €. Kuljetuspalvelun hinta riippuu kuluttajan valitsemasta määränpäästä, toimitustavasta (kuriiripalvelu, nouto) ja tavaroiden määrästä. Kuluttaja voi nähdä kuljetuspalvelun lopullisen hinnan valitessaan tavaroiden määrän, kohdeosoitteen ja toimitustavan.<br />
                        4.4. Käytettyjen ja uusien vanteiden ja renkaiden hinta ilmoitetaan yksikköhintana.<br />
                        4.5. Elinkeinonharjoittajalla on oikeus muuttaa verkkokaupassa näkyviä hintoja milloin tahansa. Jos hinnat verkkokaupassa ovat muuttuneet sen jälkeen, kun kuluttaja on antanut tilauksen ja maksanut sen, hän sitoutuu toimittamaan vastaavat tuotteet käyttäjälle tilauksen aikaan voimassa olevilla hinnoilla tai antamaan mahdollisuuden peruuttaa järjestys. Kuluttajalla ei ole oikeutta vaatia korvausta hintaerosta.5. TOIMITUSAIKA JA TOIMITUSEHDOT5.1. Jos tavaroiden sijainti on Helsinki varasto, tilatut tavarat toimitetaan kuluttajan ilmoittamaan osoitteeseen ja valinnassa ilmoitetun kuljetuspalvelun kanssa DPD: lle tai Matkahuolto: lle kuluttajalle 2-7 työpäivän kuluessa, jos tavaroiden sijainti on Vesse, Vesse-varasto – 4-9 työpäivän kuluessa . Jos tavaroiden toimitusaika on merkitty ”tilauksesta” jne., Tavarat toimitetaan kuluttajalle ulkomaisesta varastosta. Kun lasku on maksettu 1A Renkaat OY: n pankkitilille, tavarat toimitetaan kuluttajalle 3-14 työpäivän kuluessa. Jos laskut maksetaan tai vastaanotetaan lomapäivinä tai työpäivän klo 12.00 jälkeen, tilauksen toteutus alkaa seuraavana työpäivänä.<br />
                        5.2. Vanteiden ja renkaiden toimitus Helsingissä on maksutonta.<br />
                        5.3. Toimitusaika erityisalueille, kuten saarille ja syrjäisille läänille, voidaan pidentää 5 työpäivään.<br />
                        5.4. Jos tuotteen sijainniksi ilmoitetaan Varasto tai Varasto 3, tavarat toimitetaan kuluttajalle 2-7 työpäivän kuluessa maksun vastaanottamisesta 1A Renkaat OY: n pankkitilille.<br />
                        5.5. Tavarat, joiden sijainti on ”2 päivää kanssa tilauksen ”, tarkoittavat, että tavarat saapuvat 1arenkaat.fi toimistoon 2-3 työpäivän kuluessa tilauksen tekemisestä. Jos kuluttaja haluaa vastaanottaa tavarat DPD-, Matkahuoltolla tai OSC-kuriirilla, tavaroiden toimitusaika lisätään toimitusaikaan 2-3 työpäivää.<br />
                        5.6. Kun tilaat tavaroita, joiden sijainti on, on välttämätöntä ottaa yhteyttä kauppiaaseen sähköpostitse info@1arenkaat.fi, puhelimitse (+358) 40 481 7479 tai tarkempia tietoja Facebookissa ja INSTAGRAMissa.<br />
                        5.7. Toimituspaikkaan tultaessa tiedot on tarkistettava huolellisesti ja kaikki vaaditut tiedot on annettava ja oikeat. Elinkeinonharjoittaja toimittaa tavarat kuluttajalle annettujen tietojen perusteella. 1arenkaat.fi ja kuriiriyhtiö eivät ole vastuussa tuotteiden toimitusten viivästymisistä ja väärinkäsityksistä, jos viivästyminen tai väärinkäsitys johtuu kuluttajan antamien tietojen virheellisyydestä tilausta tehtäessä.6. SOPIMUKSEN PERUUTTAMINEN<br />
                        6.1. Kaikilla 1arenkaat.fi verkkokaupasta ostetuilla tuotteilla on 14 päivän palautusoikeus. LPA-lain (velkolaki) 56 §: n 1 momentin mukaan kuluttajalla on oikeus palauttaa tai vaihtaa tavara toiseen tuotteeseen ilmoittamatta syytä 14 päivän kuluessa tavaran toimittamisesta. HUOM! Lain mukaan tätä sääntöä ei sovelleta toimistoilta ostettuihin tavaroihin.<br />
                        6.2. Jos sopimus irtisanotaan, kuluttajan on tehtävä elinkeinonharjoittajalle vastaava pyyntö (jossa ilmoitetaan sähköpostiosoite info@1arenkaat.fi): kuluttajan nimi, ostopäivä, käyttötilin numero ja tilausnumero. Palauta sitten tilatut tavarat 1arenkaat.fi -verkkokauppaan välittömästi, mutta viimeistään 14 päivän kuluessa peruuttamisilmoituksen jättämisestä (LPA: n § 56² (1)). (LPA: n 56 §: n 25 momentin mukaan kuluttaja todistaa sopimuksesta luopumisen).<br />
                        6.3. Esineen palauttamisesta aiheutuvat kustannukset vastaa kuluttaja, elleivät osapuolet ole sopineet toisin.<br />
                        6.4. Tilauksen peruuttamisen jälkeen rahat tavaroista, mukaan lukien kuluttajalle aiheutuneet toimituskulut, palautetaan samalle käyttötilille, jolta tavarat on maksettu 14 päivän kuluessa siitä, kun kauppias on vastaanottanut tavarat. Elinkeinonharjoittajalle on annettu mahdollisuus viivästyttää maksua, kunnes kuluttaja on palauttanut sopimuksen kohteena olevan tavaran tai toimittanut todisteet siitä, että hän on palauttanut asian (LPA: n 561 §: n 5 momentti).<br />
                        6.5. 1arenkaat.fi-verkkokaupasta ostettuja palautettuja tavaroita (renkaat / pyörät / muut tavarat) ei saa käyttää (ajaa), asentaa tai purkaa ja vahingoittaa.<br />
                        6.6. Jos käy ilmi, että palautetut tavarat eivät täytä käyttösopimuksen kohdan 6.5 ehtoja, elinkeinonharjoittajalla on oikeus vaatia tavaran arvon alenemista.7. VASTUU<br />
                        7.1. Elinkeinonharjoittaja ja kuluttaja ovat vastuussa toisilleen vahingoista, jotka toisille osapuolille aiheutuu näiden ehtojen rikkomisesta Suomen tasavallassa voimassa olevassa lainsäädännössä säädetyissä tapauksissa ja siinä laajuudessa. Tavaroiden toimitus Suomen tasavallan ulkopuolella osapuolet ohjaavat myös EU: n lainsäädäntöä ja kansainvälistä oikeutta.<br />
                        7.2. Elinkeinonharjoittaja ei ole vastuussa tuotteen toimittamisen viivästymisestä kuluttajalle.<br />
                        7.3. Elinkeinonharjoittaja ei ole vastuussa tuotteen katoamisesta tai vahingoittumisesta, joka tehdään rahdinkuljettajalle lähetetyn lähetystilauksen (Matkahuolto, OSC ja DPD) perusteella.<br />
                        7.4. Elinkeinonharjoittaja ei ole vastuussa kuluttajan ostamista uusista tavaroista 1arenkaat.fi-sivustolta, jos se löytää toiselta myyjältä ostettuja vanteita, eikä yritys korvaa näitä kustannuksia. Jos vika havaitaan, kuluttajan on ilmoitettava siitä elinkeinonharjoittajalle mahdollisimman pian sähköpostitse, kirjoitettava hänen yhteystietonsa, laskun numero, kuvaus virheestä, liitettävä tarvittavat kopiot asiakirjoista ja kuvista.7.4.1. Elinkeinonharjoittaja ei ole vastuussa 1arenkaat.fi-verkkokaupasta ostetuista tavaroista, jotka eivät ole kauppiaan korjaamossa / teknisen asennuksen aikana, eikä uusien tuotteiden ostamisesta toiselta kauppiaalta.7.4.2. Elinkeinonharjoittaja ei ole aineellisesti vastuussa korvaavien tuotteiden ostamisesta muilta kauppiailta, jos toinen kauppias on annettu kielteisen arvion 1arenkaat.fi-verkkokaupasta ostetuista tavaroista.<br />
                        7.5. 1arenkaat.fi on vastuussa tehdystä työstä ja toimistossa hankituista ja asennetuista tavaroista.8. MENETTELY VAATIMUSTEN ESITTÄMISEKSI<br />
                        8.1. 1arenkaat.fi tarkastaa kirjallisen valituksen 15 kalenteripäivän kuluessa TKS: n 19 §: n 6 momentin jättämisestä. Jos elinkeinonharjoittaja ei pysty vastaamaan kuluttajan valitukseen 15 päivän kuluessa, elinkeinonharjoittajan on ilmoitettava asiasta kuluttajalle kirjallisesti vastaamaan kohtuullisen ajan kuluessa, TKS: n 19 §: n 6 momentti.<br />
                        8.2. Tavaravaatimuksen esittämisen aika on kaksi vuotta tavaran luovuttamisesta kuluttajalle LPA 218 §: n 2 momentti.<br />
                        8.3. Virheen sattuessa kuluttaja on velvollinen olemaan käyttämättä tavaraa ja ilmoittamaan siitä kauppiaalle välittömästi.<br />
                        8.4. Kuluttajan vaatimus ei ole ratkaistavissa, jos tavaroiden käytössä on virheitä kuluttajan syystä.<br />
                        8.5. 1arenkaat.fi -yhtiöllä on oikeus suorittaa asiantuntijatarkastus tuotteen vian syyn selvittämiseksi. Jos tutkimuksen aikana käy ilmi, että tavarat ovat aiheutuneet virheestä, takuu ei kata tavaroita ja kuluttaja maksaa tutkimuksen kustannukset.<br />
                        8.6. Vaatimus kattaa renkaat / pyörät / muut tavarat, joita ei ole asennettu ja joista seuraa välittömästi havaittavia vikoja, jotka eivät olleet kuluttajan tiedossa ostohetkellä:8.6.1. Leikat / halkeamat, jotka estävät vanteen normaalin käytön;<br />
                        8.7. Vaihdamme tuotteen tai vaihdamme sen toiseen tuotteeseen. Jos korvaavia tuotteita ei ole saatavilla, elinkeinonharjoittaja palauttaa rahat kuluttajalle.<br />
                        8.8. Käytettyjen renkaiden ja vanteiden takuu on voimassa asennuksesta alkaen, mikä on todistettu yrityksen ostokuitin perusteella.8.8.1. Seuraavat pyörien loukkaantumiset ja väärinkäytöt eivät kuulu vaatimuksen piiriin:8.8.2. Renkaiden ja pyörien vaurioituminen tieolosuhteiden vuoksi.8.8.3. Renkaiden ja pyörien vauriot, jotka aiheutuvat onnettomuuksista (onnettomuus, tulipalo jne.)8.8.4. Renkaiden ja pyörien virheellisestä käytöstä johtuvat vahingot (väärä rengaspaine, virheellinen törmäys, epätasapainotetut pyörät, vialliset iskunvaimentimet, auton ylikuormitus, ketjujen käyttö, maastoajot jne.).8.8.5. Renkaat / vanteet/ muut tavarat korjattu ja pinnoitettu.8.8.6. Tahallinen renkaiden ja pyörien vaurioituminen.8.8.7. Viat (kirjaimet, lika, naarmut, kulumisjäljet, pienet viillot tai reiät jne.), Jotka ovat syntyneet pyörien normaalista käytöstä eivätkä estä käytettyjen pyörien normaalia uudelleenkäyttöä. Muualla työpajassa vanteet takuu ei ole voimassa ja 1arenkaat.fi ei korvaa palvelujen kustannuksia, ellei toisin ole sovittu.9. HENKILÖTIEDOT JA NIIDEN KÄYTTÖ<br />
                        9.1. Kun teet tilauksia 1arenkaat.fi -sivustolla, pyydetään kuluttajan henkilötietoja (nimi, sukunimi, osoite, puhelin, sähköposti).<br />
                        9.2. 1arenkaat.fi kerää henkilötietoja vain yrityksen toimintaan (tässä tapauksessa pyörien myyntiin) tavaroiden lähettämistä tai laskun lähettämistä varten.<br />
                        9.3. Henkilötietojen käyttäjiä ovat vain ne henkilöt, joiden on tiedettävä ne myyntityön yhteydessä.<br />
                        9.4. 1arenkaat.fi tallentaa kuluttajan henkilötiedot (nimi, sukunimi, puhelin ja osoite) erilliseen yksityiseen palvelimeen myyntitarkoituksia varten.<br />
                        9.5. 1arenkaat.fi ei tallenna kuluttajapankkitietoja suorittaessaan verkkomaksuja.<br />
                        9.6. Tilauksen aikana kerättyjä tietoja ja henkilötietoja käsitellään luottamuksellisina, eikä niitä luovuteta kolmansille osapuolille.10. Erimielisyydet<br />
                        10.1. Erimielisyydet ratkaistaan Suomen tasavallan lainsäädännön mukaisesti. Kuluttajalla on oikeus kääntyä kuluttajansuojakomission puoleen. Jos osapuolet eivät pääse sopimukseen, riidat ratkaistaan läänin tuomioistuimessa.11. TÄRKEITÄ TIETOJA<br />
                        11.1. 1arenkaat.fi myy myös tavaroita kunto ”kuin uudet”, jolla voi olla käytön jälkiä (pysäköinti / asennus, kauneusvirhet jne.). Tällä tavaroiden renkaat / vanteiden / kauneusvirhet eivät vaaranna kuluttajaa millään tavalla.<br />
                        1A Renkaat OY, Y-tunnus 3104581-8 (jäljempänä elinkeinonharjoittaja) ja kuluttaja, joka tekee tilauksen 1arenkaat.fi-verkkokaupassa ja tunnistaa itsensä syöttämällä henkilökohtaiset tiedot tilaukseen, teki tämän verkkokaupan käyttöoikeussopimuksen .1. Verkkokauppa<br />
                        1.1. 1arenkaat.fi on kauppiaan luoma verkkokauppa, jonka kautta tuotteita myydään kuluttajille.2. YLEISET SÄÄNNÖKSET<br />
                        2.1. Sopimuksen osapuolia ohjaavat keskinäisiä suhteitaan Suomen tasavallan lait ja muut lait sekä e-kaupan käyttösopimuksessa oleva sopimus.<br />
                        2.2. Kauppiaalla on oikeus tehdä muutoksia tarjottuun verkkokauppapalveluun milloin tahansa.<br />
                        2.3. Elinkeinonharjoittajalla on oikeus muuttaa yksipuolisesti käyttöoikeusehtoja ilman velvollisuutta ilmoittaa siitä kuluttajalle.3. TUOTTEET JA OSTOKSEN TEKEMINENKuluttajalla on mahdollisuus valita sopiva tuote 1arenkaat.fi -sivustolta ja lisätä se ostoskoriin. Verkkosivusto kuvaa tavarat sekä havainnollisina että todellisina kuvina.<br />
                        3.1. Kuluttajalla on mahdollisuus valita oikea tuote vanteen koon mukaan ja lisätä se ostoskoriin. Voit sitten etsiä verkkosivustolta muita sinua kiinnostavia vanteiden kokoja ja lisätä ne tarvittaessa ostoskoriin. Renkaiden ja vanteiden on esitetty 4, 3, 2 ja 1 määränä. Ei ole mahdollista ostaa yhtä vanteen (1 kpl.) ja paria (2 kpl.) sarjastä. Voisi kirjoittaa sähköpostin ostaaksesi yhden vanteen sarjastä.<br />
                        3.2. Jos muita valintoja ei ole tehty, alla olevat toimitustiedot on täytettävä ja kuljetustapa valittava. Ennen kuin ostat, tarkista annettujen tietojen oikeellisuus, kiinnitä huomiota tuotetietoihin (tuotteen kunto, sijainti, määrä) ja varmista vanteen koko on oike. Seuraavaksi sinun tulee lukea ja hyväksyä 1arenkaat.fi: n ostoehdot ja painaa OSTAA-painiketta.<br />
                        3.3. Voit maksaa tavaroista kokonaisuudessaan verkkosivustolla. Koko lasku lähetetään automaattisesti kuluttajan kirjoittamaan sähköpostiin.<br />
                        3.4. Tavaroiden maksu suoritetaan Montonion kautta. Maksuvaihtoehdot: -Suomi: Aktia, Ålandin pankki, Danske, Handelsbanken, Nordea, Oma Säästopankki, Pohjola, POP Pankki, S-Pankki, Säästopankki-Visa / Mastercard -kortti. Kauppiaan pankkien tiedot näkyvät verkkosivustolla. Paina seuraavaksi OSTAA-painiketta. Sitten kuluttaja ohjataan Internet-pankkiin. Jos maksu on suoritettu Internet-pankissa, on erittäin tärkeää muistaa, että kuluttaja palaa takaisin 1arenkaat.fi -sivustolle, jolla osto tehtiin. Paina Internet-pankissa Takaisin kauppiaan-painiketta.3.5. Meie kumppaneita osamaksujen alalla ovat…<br />
                        3.6. Kuluttajat voivat tilata tavaroita ilmaiseksi 1arenkaat.fi -toimistossä, joka sijaitsee Helsingissä, Valokaari 10: ssä tai yhteistyökumppaneista. Tavarat voidaan tilata myös kuluttajan ilmoittamaan osoitteeseen. Jälkimmäisessä tapauksessa tavaroiden lähettämisen edellytyksenä on maksaa koko summa tilauksen mukaan. Jos kuluttajan osoite on Manner-Suomen sisällä, toimitus on 25 eur 2 kpl ja 40 eur 4kpl ja en riippuu toimituspaikasta. Suomessa Matkahuollon hinnastot ovat voimassa. Hinnat voidaan aina kysyaa toimittajalta. Toimitushinta lisätään automaattisesti tavaroiden hintaan valitsemalla oikea toimitusmenetelmä ostoksen yhteydessä.3.7. Haluttaessa on mahdollista suorittaa renkaanvaihto 1arenkaat.fi -toimistossa Helsingissä tai yhteistyökumppaneilla.3.8. Elinkeinonharjoittajan ja kuluttajan välisen sopimuksen katsotaan tehdyn alkaen tilausvahvistuksen mukaan maksettavan määrän vastaanottamisesta 1A Renkaat OY: n käyttötilille.3.9. Verkkokaupasta tehty ”maksamaton tilaus”, josta kuluttaja ei ole suorittanut siirtoa 3 työpäivän kuluessa, peruutetaan.4. HINNAT4.1. Kaikki verkkokaupan hinnat ovat euroissa ja sisältävät arvonlisäveron.4.2. Neljän (4) ja enammään renkaan tilaamisen kuljetuskustannukset Suomessä ovat 25-40eur.<br />
                        4.3. Jos tilaus tehdään alle neljästä (4) renkaasta, kuljetuksen hinta on 25 – 40 €. Kuljetuspalvelun hinta riippuu kuluttajan valitsemasta määränpäästä, toimitustavasta (kuriiripalvelu, nouto) ja tavaroiden määrästä. Kuluttaja voi nähdä kuljetuspalvelun lopullisen hinnan valitessaan tavaroiden määrän, kohdeosoitteen ja toimitustavan.<br />
                        4.4. Käytettyjen ja uusien vanteiden ja renkaiden hinta ilmoitetaan yksikköhintana.<br />
                        4.5. Elinkeinonharjoittajalla on oikeus muuttaa verkkokaupassa näkyviä hintoja milloin tahansa. Jos hinnat verkkokaupassa ovat muuttuneet sen jälkeen, kun kuluttaja on antanut tilauksen ja maksanut sen, hän sitoutuu toimittamaan vastaavat tuotteet käyttäjälle tilauksen aikaan voimassa olevilla hinnoilla tai antamaan mahdollisuuden peruuttaa järjestys. Kuluttajalla ei ole oikeutta vaatia korvausta hintaerosta.5. TOIMITUSAIKA JA TOIMITUSEHDOT5.1. Jos tavaroiden sijainti on Helsinki varasto, tilatut tavarat toimitetaan kuluttajan ilmoittamaan osoitteeseen ja valinnassa ilmoitetun kuljetuspalvelun kanssa DPD: lle tai Matkahuolto: lle kuluttajalle 2-7 työpäivän kuluessa, jos tavaroiden sijainti on Vesse, Vesse-varasto – 4-9 työpäivän kuluessa . Jos tavaroiden toimitusaika on merkitty ”tilauksesta” jne., Tavarat toimitetaan kuluttajalle ulkomaisesta varastosta. Kun lasku on maksettu 1A Renkaat OY: n pankkitilille, tavarat toimitetaan kuluttajalle 3-14 työpäivän kuluessa. Jos laskut maksetaan tai vastaanotetaan lomapäivinä tai työpäivän klo 12.00 jälkeen, tilauksen toteutus alkaa seuraavana työpäivänä.<br />
                        5.2. Vanteiden ja renkaiden toimitus Helsingissä on maksutonta.<br />
                        5.3. Toimitusaika erityisalueille, kuten saarille ja syrjäisille läänille, voidaan pidentää 5 työpäivään.<br />
                        5.4. Jos tuotteen sijainniksi ilmoitetaan Varasto tai Varasto 3, tavarat toimitetaan kuluttajalle 2-7 työpäivän kuluessa maksun vastaanottamisesta 1A Renkaat OY: n pankkitilille.<br />
                        5.5. Tavarat, joiden sijainti on ”2 päivää kanssa tilauksen ”, tarkoittavat, että tavarat saapuvat 1arenkaat.fi toimistoon 2-3 työpäivän kuluessa tilauksen tekemisestä. Jos kuluttaja haluaa vastaanottaa tavarat DPD-, Matkahuoltolla tai OSC-kuriirilla, tavaroiden toimitusaika lisätään toimitusaikaan 2-3 työpäivää.<br />
                        5.6. Kun tilaat tavaroita, joiden sijainti on, on välttämätöntä ottaa yhteyttä kauppiaaseen sähköpostitse info@1arenkaat.fi, puhelimitse (+358) 40 481 7479 tai tarkempia tietoja Facebookissa ja INSTAGRAMissa.<br />
                        5.7. Toimituspaikkaan tultaessa tiedot on tarkistettava huolellisesti ja kaikki vaaditut tiedot on annettava ja oikeat. Elinkeinonharjoittaja toimittaa tavarat kuluttajalle annettujen tietojen perusteella. 1arenkaat.fi ja kuriiriyhtiö eivät ole vastuussa tuotteiden toimitusten viivästymisistä ja väärinkäsityksistä, jos viivästyminen tai väärinkäsitys johtuu kuluttajan antamien tietojen virheellisyydestä tilausta tehtäessä.6. SOPIMUKSEN PERUUTTAMINEN<br />
                        6.1. Kaikilla 1arenkaat.fi verkkokaupasta ostetuilla tuotteilla on 14 päivän palautusoikeus. LPA-lain (velkolaki) 56 §: n 1 momentin mukaan kuluttajalla on oikeus palauttaa tai vaihtaa tavara toiseen tuotteeseen ilmoittamatta syytä 14 päivän kuluessa tavaran toimittamisesta. HUOM! Lain mukaan tätä sääntöä ei sovelleta toimistoilta ostettuihin tavaroihin.<br />
                        6.2. Jos sopimus irtisanotaan, kuluttajan on tehtävä elinkeinonharjoittajalle vastaava pyyntö (jossa ilmoitetaan sähköpostiosoite info@1arenkaat.fi): kuluttajan nimi, ostopäivä, käyttötilin numero ja tilausnumero. Palauta sitten tilatut tavarat 1arenkaat.fi -verkkokauppaan välittömästi, mutta viimeistään 14 päivän kuluessa peruuttamisilmoituksen jättämisestä (LPA: n § 56² (1)). (LPA: n 56 §: n 25 momentin mukaan kuluttaja todistaa sopimuksesta luopumisen).<br />
                        6.3. Esineen palauttamisesta aiheutuvat kustannukset vastaa kuluttaja, elleivät osapuolet ole sopineet toisin.<br />
                        6.4. Tilauksen peruuttamisen jälkeen rahat tavaroista, mukaan lukien kuluttajalle aiheutuneet toimituskulut, palautetaan samalle käyttötilille, jolta tavarat on maksettu 14 päivän kuluessa siitä, kun kauppias on vastaanottanut tavarat. Elinkeinonharjoittajalle on annettu mahdollisuus viivästyttää maksua, kunnes kuluttaja on palauttanut sopimuksen kohteena olevan tavaran tai toimittanut todisteet siitä, että hän on palauttanut asian (LPA: n 561 §: n 5 momentti).<br />
                        6.5. 1arenkaat.fi-verkkokaupasta ostettuja palautettuja tavaroita (renkaat / pyörät / muut tavarat) ei saa käyttää (ajaa), asentaa tai purkaa ja vahingoittaa.<br />
                        6.6. Jos käy ilmi, että palautetut tavarat eivät täytä käyttösopimuksen kohdan 6.5 ehtoja, elinkeinonharjoittajalla on oikeus vaatia tavaran arvon alenemista.7. VASTUU<br />
                        7.1. Elinkeinonharjoittaja ja kuluttaja ovat vastuussa toisilleen vahingoista, jotka toisille osapuolille aiheutuu näiden ehtojen rikkomisesta Suomen tasavallassa voimassa olevassa lainsäädännössä säädetyissä tapauksissa ja siinä laajuudessa. Tavaroiden toimitus Suomen tasavallan ulkopuolella osapuolet ohjaavat myös EU: n lainsäädäntöä ja kansainvälistä oikeutta.<br />
                        7.2. Elinkeinonharjoittaja ei ole vastuussa tuotteen toimittamisen viivästymisestä kuluttajalle.<br />
                        7.3. Elinkeinonharjoittaja ei ole vastuussa tuotteen katoamisesta tai vahingoittumisesta, joka tehdään rahdinkuljettajalle lähetetyn lähetystilauksen (Matkahuolto, OSC ja DPD) perusteella.<br />
                        7.4. Elinkeinonharjoittaja ei ole vastuussa kuluttajan ostamista uusista tavaroista 1arenkaat.fi-sivustolta, jos se löytää toiselta myyjältä ostettuja vanteita, eikä yritys korvaa näitä kustannuksia. Jos vika havaitaan, kuluttajan on ilmoitettava siitä elinkeinonharjoittajalle mahdollisimman pian sähköpostitse, kirjoitettava hänen yhteystietonsa, laskun numero, kuvaus virheestä, liitettävä tarvittavat kopiot asiakirjoista ja kuvista.7.4.1. Elinkeinonharjoittaja ei ole vastuussa 1arenkaat.fi-verkkokaupasta ostetuista tavaroista, jotka eivät ole kauppiaan korjaamossa / teknisen asennuksen aikana, eikä uusien tuotteiden ostamisesta toiselta kauppiaalta.7.4.2. Elinkeinonharjoittaja ei ole aineellisesti vastuussa korvaavien tuotteiden ostamisesta muilta kauppiailta, jos toinen kauppias on annettu kielteisen arvion 1arenkaat.fi-verkkokaupasta ostetuista tavaroista.<br />
                        7.5. 1arenkaat.fi on vastuussa tehdystä työstä ja toimistossa hankituista ja asennetuista tavaroista.8. MENETTELY VAATIMUSTEN ESITTÄMISEKSI<br />
                        8.1. 1arenkaat.fi tarkastaa kirjallisen valituksen 15 kalenteripäivän kuluessa TKS: n 19 §: n 6 momentin jättämisestä. Jos elinkeinonharjoittaja ei pysty vastaamaan kuluttajan valitukseen 15 päivän kuluessa, elinkeinonharjoittajan on ilmoitettava asiasta kuluttajalle kirjallisesti vastaamaan kohtuullisen ajan kuluessa, TKS: n 19 §: n 6 momentti.<br />
                        8.2. Tavaravaatimuksen esittämisen aika on kaksi vuotta tavaran luovuttamisesta kuluttajalle LPA 218 §: n 2 momentti.<br />
                        8.3. Virheen sattuessa kuluttaja on velvollinen olemaan käyttämättä tavaraa ja ilmoittamaan siitä kauppiaalle välittömästi.<br />
                        8.4. Kuluttajan vaatimus ei ole ratkaistavissa, jos tavaroiden käytössä on virheitä kuluttajan syystä.<br />
                        8.5. 1arenkaat.fi -yhtiöllä on oikeus suorittaa asiantuntijatarkastus tuotteen vian syyn selvittämiseksi. Jos tutkimuksen aikana käy ilmi, että tavarat ovat aiheutuneet virheestä, takuu ei kata tavaroita ja kuluttaja maksaa tutkimuksen kustannukset.<br />
                        8.6. Vaatimus kattaa renkaat / pyörät / muut tavarat, joita ei ole asennettu ja joista seuraa välittömästi havaittavia vikoja, jotka eivät olleet kuluttajan tiedossa ostohetkellä:8.6.1. Leikat / halkeamat, jotka estävät vanteen normaalin käytön;<br />
                        8.7. Vaihdamme tuotteen tai vaihdamme sen toiseen tuotteeseen. Jos korvaavia tuotteita ei ole saatavilla, elinkeinonharjoittaja palauttaa rahat kuluttajalle.<br />
                        8.8. Käytettyjen renkaiden ja vanteiden takuu on voimassa asennuksesta alkaen, mikä on todistettu yrityksen ostokuitin perusteella.8.8.1. Seuraavat pyörien loukkaantumiset ja väärinkäytöt eivät kuulu vaatimuksen piiriin:8.8.2. Renkaiden ja pyörien vaurioituminen tieolosuhteiden vuoksi.8.8.3. Renkaiden ja pyörien vauriot, jotka aiheutuvat onnettomuuksista (onnettomuus, tulipalo jne.)8.8.4. Renkaiden ja pyörien virheellisestä käytöstä johtuvat vahingot (väärä rengaspaine, virheellinen törmäys, epätasapainotetut pyörät, vialliset iskunvaimentimet, auton ylikuormitus, ketjujen käyttö, maastoajot jne.).8.8.5. Renkaat / vanteet/ muut tavarat korjattu ja pinnoitettu.8.8.6. Tahallinen renkaiden ja pyörien vaurioituminen.8.8.7. Viat (kirjaimet, lika, naarmut, kulumisjäljet, pienet viillot tai reiät jne.), Jotka ovat syntyneet pyörien normaalista käytöstä eivätkä estä käytettyjen pyörien normaalia uudelleenkäyttöä. Muualla työpajassa vanteet takuu ei ole voimassa ja 1arenkaat.fi ei korvaa palvelujen kustannuksia, ellei toisin ole sovittu.9. HENKILÖTIEDOT JA NIIDEN KÄYTTÖ<br />
                        9.1. Kun teet tilauksia 1arenkaat.fi -sivustolla, pyydetään kuluttajan henkilötietoja (nimi, sukunimi, osoite, puhelin, sähköposti).<br />
                        9.2. 1arenkaat.fi kerää henkilötietoja vain yrityksen toimintaan (tässä tapauksessa pyörien myyntiin) tavaroiden lähettämistä tai laskun lähettämistä varten.<br />
                        9.3. Henkilötietojen käyttäjiä ovat vain ne henkilöt, joiden on tiedettävä ne myyntityön yhteydessä.<br />
                        9.4. 1arenkaat.fi tallentaa kuluttajan henkilötiedot (nimi, sukunimi, puhelin ja osoite) erilliseen yksityiseen palvelimeen myyntitarkoituksia varten.<br />
                        9.5. 1arenkaat.fi ei tallenna kuluttajapankkitietoja suorittaessaan verkkomaksuja.<br />
                        9.6. Tilauksen aikana kerättyjä tietoja ja henkilötietoja käsitellään luottamuksellisina, eikä niitä luovuteta kolmansille osapuolille.10. Erimielisyydet<br />
                        10.1. Erimielisyydet ratkaistaan Suomen tasavallan lainsäädännön mukaisesti. Kuluttajalla on oikeus kääntyä kuluttajansuojakomission puoleen. Jos osapuolet eivät pääse sopimukseen, riidat ratkaistaan läänin tuomioistuimessa.11. TÄRKEITÄ TIETOJA<br />
                        11.1. 1arenkaat.fi myy myös tavaroita kunto ”kuin uudet”, jolla voi olla käytön jälkiä (pysäköinti / asennus, kauneusvirhet jne.). Tällä tavaroiden renkaat / vanteiden / kauneusvirhet eivät vaaranna kuluttajaa millään tavalla.<br />
                    </p>
                </div>
            </div>
        </section>
    );
}

export default DeliveryAndReturn